[package]
name = "kaisen_yao_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "^0.11", features = ["blocking"] }
rusqlite = "^0.30"
csv = "^1.3"
assert_cmd = "^2.0"
predicates = "0.9"